name: Python CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  branch-name-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch naming convention
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          BRANCH_NAME=${GITHUB_HEAD_REF#refs/heads/}
        else
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
        fi
        
        if [[ "$BRANCH_NAME" == "main" ]]; then
          echo "❌ Don't work directly on main branch!"
          exit 1
        fi
        
        if [[ ! "$BRANCH_NAME" =~ ^(feature|fix|docs|refactor)/ ]]; then
          echo "❌ Branch name must start with feature/, fix/, docs/, or refactor/"
          echo "Current branch: $BRANCH_NAME"
          exit 1
        fi

  # Temporarily comment out test and security jobs until we have code
  # test:
  #   needs: branch-name-check
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.9", "3.10", "3.11"]

  #   steps:
  #   - uses: actions/checkout@v3
    
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: ${{ matrix.python-version }}
        
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
        
  #   - name: Run tests
  #     run: |
  #       pytest
        
  #   - name: Type checking
  #     run: |
  #       mypy .
        
  #   - name: Lint
  #     run: |
  #       black . --check
  #       isort . --check

  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
    
  #   - name: Security dependency scan
  #     uses: pypa/gh-action-pip-audit@v1.0.8 